### ISSUE TITLE
Is it useful also to communicate across different windows?

### ISSUE THREAD

**Issue by ldetomi** [wingify/across-tabs#12]
Hi,
As subject, I would like to know if this plugin could useful also for multi-window environment or only in multi tab ones.

Thanks

**Comment by softvar** [comment]
Hey @ldetomi 
Yes, it does work. 

Any tab/window opened after clicking a link on a page, and both tabs/windows having across-tabs library initialized, will be able to communicate with each other.

For communication, `postMessage` is being used. Check this out - https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

Let me know if you still have any doubts :)
