### ISSUE TITLE
If multiple child tabs are opened simultaneously, only one of them works correctly.

### ISSUE THREAD

**Issue by Punit-wingify** [wingify/across-tabs#15]
Steps to replicate:
1) Create a button on parent window which can open a new child tab.
2) Ensure that 'data-tab-opener' isn't used on that button.
3) Click that button multiple times at the same time.
4) Ids/references will be assigned to the first tab which initiated the handshake and not to the rest resulting in incorrect behavior.

**Comment by jpike88** [comment]
Wow why?

**Comment by SenthilKumaranC** [comment]
Same thing happening to me. Now added delay between tab opening , it works fine.
