### ISSUE TITLE
Allow for custom stringifier

### ISSUE THREAD

**Issue by planttheidea** [wingify/across-tabs#16]
Based on the results (and looking at the code [here](https://github.com/wingify/across-tabs/blob/f2d0a5b6f1d6b512ba1d176efa80575445e705ab/src/utils/tab.js#L37) and [here](https://github.com/wingify/across-tabs/blob/2864b1d30cd5e6affb5765c66640dc8de1c47a3b/src/child.js#L223) it looks like the native `JSON.stringify` is used to serialize the transmission, and then naturally the native `JSON.parse` is used to deserialize the message. My question is ... would it be possible to provide custom `replacer` / `reviver` methods, so that we can pass forms of data not traditionally supported by `JSON.stringify`? A simple example would be `Map` or `Set`, which most browsers do not support stringifying natively (even though it is part of the spec), and only recently did `core-js` do a polyfill for it.

Something like this should be relatively straightforward to apply, just providing a couple of new options that would default to `undefined` so as not to break the existing functionality, and then passing those options to the calls of `JSON.stringify` and `JSON.parse`. What do you think?

**Comment by softvar** [comment]
Hey @planttheidea 
It makes sense to me. If you can help in contributing the feature, it would be appreciated.

Thanks
