### ISSUE TITLE
Home page spelling mistakes

### ISSUE THREAD

**Issue by lemon2015** [wingify/across-tabs#18]
Hi, when I read the contents in the index page , I found a misspelling in the produce of `broadCastAll`  method of API part - `parent.broadCastAll('Hello my dear Child! A greeting from Parent.'});`  ,maybe it should be `parent.broadCastAll('Hello my dear Child! A greeting from Parent.');` - remove the `}`.

**Comment by softvar** [comment]
Thanks for pointing that out. Will fix this soon.
