### ISSUE TITLE
As Chrome Extension: Open new tab posts message multiple times

### ISSUE THREAD

**Issue by cj-prog** [wingify/across-tabs#30]
First of all: I love across-tabs. It's easy to use and works very fine for my web app!

I've implemented across-tabs in my **Chrome Extension** using **Vue** but it doesn't work as expected.

If I open a new tab the post message is send **4 times instead of one**. So it is impossible to make a clean handshake.

I have created a **minimal example** of this problem and pushed it to **GitHub**: [Across-Tabs-Vue-Chrome-Extension-Boilerplate](https://github.com/cj-prog/across-tabs-vue-chrome-extension-boilerplate)

(If we can solve the problem, you are welcome to reference my project.)

The boilerplate works as Web App and as Chrome Extension. 

If I run the project as Web App, it works fine:
![Web App](https://user-images.githubusercontent.com/17256763/73599930-ee3b1500-4549-11ea-871c-c8052e8e8b7a.jpg)

But as Chrome Extension not:
![Chrome Extension](https://user-images.githubusercontent.com/17256763/73599927-e8453400-4549-11ea-8f17-db4957e14a0f.jpg)

I am really grateful for any support.

**Comment by cj-prog** [comment]
Okay, I've fixed the bug and you can close this issue.

I've replaced the HtmlWebpackPlugin by CopyWebPackPlugin to avoid loading twice.

It seems to be a bug in the HtmlWebpackPlugin.

I you'd like to have a look: https://github.com/cj-prog/across-tabs-vue-chrome-extension-boilerplate

**Comment by softvar** [comment]
It's good to hear you were able to make it running :)
