### ISSUE TITLE
Open new popup (not just tab)

### ISSUE THREAD

**Issue by stasberkov** [wingify/across-tabs#32]
Is it possible to open new popup window but not just tab?

**Comment by benvan** [comment]
Yes - under the hood this library just calls [window.open](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) - you can provide the `windowFeatures` (as in, third) argument via your config, e.g.

```javascript
parent.openNewTab({
  url: "example.com",
  windowFeatures: "toolbar=no,location=yes,directories=no,status=no,menubar=no,scrollbars=yes,resizable=yes,copyhistory=no,width=599,height=600"
})
```

**Comment by stasberkov** [comment]
thank you so much!
