### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by sureshkodur** [wingify/across-tabs#34]
Hi, Can you explain how can I use it in an angular (2+) application?? Thanks in advance

**Comment by ParthJani** [comment]
Visit this site for answer http://technotrendnow.today/day-3.html

**Comment by softvar** [comment]
@sureshkodur Sorry to say I have never used Angular 2. But I'm pretty sure you will get a lot of help from online resources and maybe asking on StackOverflow.

Since the issue is not related to the library itself, I'm closing it.
