### ISSUE TITLE
How can I get msg send by parent tab ?

### ISSUE THREAD

**Issue by wenkanglin** [wingify/across-tabs#6]
I check the api doc and I use the `broadCastAll` method to broadcast msg, but I can't get msg from child tab. Is there anything I have missed ?

```
// parent.html
// I can't get the msg send by child
parent.broadCastall(msg);

// child.html
// I also can't get the msg send by parent
child.sendMessageToParent(msg);
```

**Comment by softvar** [comment]
Check the example folder.
This file [child.html](https://github.com/wingify/across-tabs/blob/master/example/vanilla-js/child.html) registers a listener function `onParentCommunication`

```
var child = new AcrossTabs.Child({
	onReady: onReady,
	onInitialize: onInitialize,
        onParentCommunication: onParentCommunication
})

function onParentCommunication(dataReceived) {
	// do stuff with dataReceived
};
```

**Comment by softvar** [comment]
Hope, your issue is now resolved.
The issue should be closed now.

**Comment by wenkanglin** [comment]
@softvar perfect ! Thank you for your wonderful answer
