### ISSUE TITLE
child tab name

### ISSUE THREAD

**Issue by m-hume** [wingify/across-tabs#7]
Is it just me or does the vanila-js example have the child tab missing its name?
![screenshot-2017-9-16 child tab](https://user-images.githubusercontent.com/3430210/30510916-d0e2fa62-9ac5-11e7-9e7f-4ef79c6b13df.png)

**Comment by m-hume** [comment]
Looks like the vue-js example also has the issue

**Comment by softvar** [comment]
Hey @m-hume ,
Yea, this likes an issue. Will debug it soon

**Comment by softvar** [comment]
Thanks for reporting this @m-hume 
It's fixed now in v1.0.3.
